export const SET_LOADING = 'SET_LOADING';
export const SET_EMPLOYEES = 'SET_EMPLOYEES';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const HANDLE_PAGE = 'HANDLE_PAGE';
export const HANDLE_DETAILED_PAGE = 'HANDLE_DETAILED_PAGE';
export const SET_EMPLOYEE_DETAILS = 'SET_EMPLOYEE_DETAILS';
